spring:
  application:
    name: userapp
  profiles:
    #选择使用的配置文件
    active: dev
server:
  port: 8088
vo:
  name: aa
  age: 20
  gender: 1
---
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update #自动更新和创建表
  profiles: dev
  datasource:
    url: jdbc:mysql://118.25.7.77:3306/demo?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver