spring:
  application:
    name: rabbitapp
  profiles:
    #选择使用的配置文件
    active: dev
server:
  port: 8080
logbook:
  format:
    style: http
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://118.25.7.77:3306/demo?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: 118.25.7.77
    username: admin
    password: 123456
    port: 5672
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1 #从队列每次取一个
        auto-startup: true
        default-requeue-rejected: true #失败后重试